name: SSR

on: push

jobs:
  website:
    if: "startsWith(github.event.commits[0].message, 'release')"
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: install
        run: yarn install

      - name: pre-build
        run: |
          yarn run ssr:build

      # - name: to-delon-builds
      #   run: |
      #     bash ./scripts/ci/build-artifacts-site.sh -ssr
      #   env:
      #     ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
